### PR TITLE
Add support for Lace

### PR DESCRIPTION
**Pull request by jeremybarnes2342**
Lace is now live on mainnet (and supports CIP-30)! https://twitter.com/lace_io/status/1645755160935772161 

LGTM 🎉

### CODE REVIEW

**Review by sennykalidien — APPROVED** [review]

**Comment by sennykalidien** [comment]
Glad to see this PR, would love to offer the support of Lace as a dApp connector soon 😀

**Comment by jeremybarnes2342** [comment]
> Are you sure lace has implemented the CIP-30 specs? I did some testing and they are still missing 🤔

I didn't personally do any testing... but according to https://www.cardano-caniuse.io Lace has full API compatibility..

What specifically wasn't working?

**Comment by mrcnk** [comment]
> Are you sure lace has implemented the CIP-30 specs? I did some testing and they are still missing 🤔

Hi @abdelkrimdev, I'm one of Lace Browser's devs. Let me know what's off, we would love to see Mesh supporting Lace.

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Review by abdelkrimdev — APPROVED** [review]

**Comment by jinglescode** [comment]
@mrcnk, just wanna keep the conversation open, according to @abdelkrimdev:
> lace are doing something wrong when updating the `window.cardano` object

**Pull request merged**
